spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/Cinema_DB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # Xóa DB cũ và làm lại từ đầu để apply schema mới nhất
    show-sql: true
    defer-datasource-initialization: true # Chạy file data.sql sau khi Hibernate tạo bảng xong
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always # Luôn chạy file data.sql khi khởi động
